import { useState, useEffect } from 'react'

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { onAuthStateChanged } from 'firebase/auth'
import { firebaseAuth } from '../firebaseConfig';
import AppPressable from '../components/ui/AppPressable'
import ContentShell from '../components/ui/ContentShell'
import { TestIds } from '../constants/testIds'
import { useResponsiveLayout, tabletStyle } from '../hooks/useResponsiveLayout'

export default function Home({navigation: {navigate}}) {
  const [loading, setLoading] = useState(true)
  const { isTablet, select } = useResponsiveLayout()

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(firebaseAuth, (user) => {
      if (user) navigate('Dashboard')
      else setLoading(false)
    })
    return unsubscribe
  }, [navigate])

  const insets = useSafeAreaInsets()

  return (
    <>
      {loading ?
        <View style={styles.loadingRoot}>
          <Text style={styles.loadingText}>Loading...</Text>
        </View>
      :
        <View style={[styles.root, {
          paddingTop: insets.top,
          paddingBottom: insets.bottom
        }]}>
          <ContentShell variant="form" style={styles.shell}>
            <View style={tabletStyle(isTablet, styles.modal, tabletStyles.modal)}>
              <Text style={tabletStyle(isTablet, styles.bigHeader, tabletStyles.bigHeader)}>ORGANIZE</Text>
              <Text style={styles.subheading}>with</Text>
              <Text style={tabletStyle(isTablet, styles.subheading1, tabletStyles.subheading1)}>MyElephantApp</Text>
              <View style={styles.wrapperContainer}>
                <AppPressable
                  testID={TestIds.home.signIn}
                  accessibilityLabel="Sign In or Sign Up"
                  style={tabletStyle(isTablet, styles.button, tabletStyles.button)}
                  onPress={() => navigate('Sign In/Sign Up')}
                >
                    <Text style={styles.buttonText}>Sign In/Sign Up</Text>
                </AppPressable>
                <AppPressable
                  testID={TestIds.home.about}
                  accessibilityLabel="I have a question"
                  style={tabletStyle(isTablet, styles.button, tabletStyles.button)}
                  onPress={() => navigate('About')}
                >
                    <Text style={styles.buttonText}>I have a question</Text>
                </AppPressable>
              </View>
              <Text style={[styles.subheading, { marginTop: select(24, 32) }]}>Take control of your personal information</Text>
              <Text style={tabletStyle(isTablet, styles.tagline, tabletStyles.tagline)}>*A portion of all proceeds generated by My Elephant App will be donated to saving endangered Elephants around the globe</Text>
            </View>
          </ContentShell>
          <StatusBar style="auto" />
        </View>
      }
    </>
  );
}

const styles = StyleSheet.create({
  loadingRoot: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#593060',
  },
  loadingText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 25,
  },
  root: {
    flex: 1,
    backgroundColor: '#593060',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shell: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  modal: {
    width: '90%',
    maxWidth: 480,
    alignSelf: 'center',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 10,
  },
  bigHeader: {
    color: 'white',
    fontSize: 60,
    textAlign: 'center',
    fontWeight: '800',
    marginBottom: 16,
  },
  subheading: {
    color: 'white',
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '600',
  },
  subheading1: {
    color: 'white',
    textAlign: 'center',
    fontSize: 35,
    fontWeight: '700',
    marginBottom: 28,
  },
  tagline: {
    color: 'white',
    textAlign: 'center',
    fontSize: 10,
    fontWeight: '600',
    marginTop: 28,
    paddingHorizontal: 12,
  },
  wrapperContainer: {
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
  },
  button: {
    width: '75%',
    borderRadius: 25,
    backgroundColor: '#FFE562',
    paddingVertical: 10,
    marginBottom: 14,
  },
  buttonText: {
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '700',
    color: '#593060',
  },
});

const tabletStyles = StyleSheet.create({
  modal: {
    width: '100%',
    paddingVertical: 24,
  },
  bigHeader: {
    fontSize: 72,
    marginBottom: 24,
  },
  subheading1: {
    fontSize: 40,
    marginBottom: 40,
  },
  button: {
    width: '100%',
    maxWidth: 360,
    paddingVertical: 14,
    marginBottom: 16,
  },
  tagline: {
    fontSize: 13,
    marginTop: 40,
    paddingHorizontal: 16,
    lineHeight: 18,
  },
})
