import { useState } from 'react';

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View, TouchableOpacity, Image } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { firebaseAuth } from '../firebaseConfig';

import {
  useFonts,
  Anybody_700Bold,
  Anybody_900Black,
} from '@expo-google-fonts/anybody'


export default function Home({navigation: {navigate}}) {

  //initialize state for loading, instantiate auth object
  const [loading, setLoading] = useState(true)
  const auth  = firebaseAuth

  const [fontsLoaded] = useFonts({
    Anybody_700Bold,
    Anybody_900Black
  })

  if (!fontsLoaded) return null

  //if user data is returned from firebaseAuth object, navigate to dashboard screen
  auth.onAuthStateChanged(user => {
    if (user) navigate('Dashboard')
    else setLoading(false)
  })

  const insets = useSafeAreaInsets()

  return (
    <>
      {loading ?
        <View style={{width: '100%', height: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', backgroundColor: '#593060'}}>
          <Text style={{
            color: 'white',
            fontWeight: '600',
            fontSize: 25
          }}>Loading...</Text>
        </View>
      :
        <View style={{
          flex: 1,
          backgroundColor: '#593060',
          alignItems: 'center',
          justifyContent: 'center',
          paddingTop: insets.top,
          paddingBottom: insets.bottom
        }}>
          {/* <Image source={require('../assets/elephant_bg.jpg')} style={styles.bgImg}/> */}
          <View style={styles.modal}>
            <Text style={[{fontFamily: 'Anybody_900Black'}, styles.bigHeader]}>ORGANIZE</Text>
            <Text style={[{fontFamily: 'Anybody_700Bold'}, styles.subheading]}>with</Text>
            <Text style={[{fontFamily: 'Anybody_700Bold'}, styles.subheading1]}>MyElephantApp</Text>
            <View style={styles.wrapperContainer}>
              <TouchableOpacity style={styles.button} onPress={() => navigate('Sign In/Sign Up')}>
                  <Text style={[{fontFamily: 'Anybody_700Bold'}, styles.buttonText]}>Sign In/Sign Up</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.button} onPress={() => navigate('About')}>
                  <Text style={[{fontFamily: 'Anybody_700Bold'}, styles.buttonText]}>I have a question</Text>
              </TouchableOpacity>
            </View>
            <Text style={[{fontFamily: 'Anybody_700Bold'}, styles.subheading, { marginTop: '10%' }]}>Take control of your personal information</Text>
            <Text style={[{fontFamily: 'Anybody_700Bold'}, styles.tagline]}>*A portion of all proceeds generated by My Elephant App will be donated to saving endangered Elephants around the globe</Text>  
          </View>
          <StatusBar style="auto" />
        </View>
      }
    </>
  );
}

const styles = StyleSheet.create({
  bgImg: {
    objectFit: 'scale-down',
    opacity: .25
  },
  modal: {
    width: '90%',
    height: '60%',
    paddingBottom: 10,
    position: 'absolute',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center'
  },
  bigHeader: {
    color: 'white',
    fontSize: 60,
    textAlign: 'center',
    fontWeight: '700',
    marginBottom: '6%'
  },
  subheading: {
    color: 'white',
    textAlign: 'center',
    fontSize: 20,
    marginBottom: '2.5%'
  },
  subheading1: {
    color: 'white',
    textAlign: 'center',
    fontSize: 30,
    marginBottom: '2.5%',
  },
  wrapperContainer: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      width: '100%',
  },
  button: {
    width: '60%',
    borderRadius: 10,
    backgroundColor: '#FFE562',
    paddingTop: '2%',
    paddingBottom: '2%',
    marginTop: '5%',
  },
  buttonText: {
    textAlign: 'center',
    fontSize: 14,
    width: '100%',
    color: '#44154B'
  },
  tagline: {
    color: 'white', 
    textAlign: 'center', 
    width: '90%',
    paddingTop: '15%',
    fontSize: 10
  }
});
